# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  name: Hosted VS2017
  demands:
  - msbuild
  - visualstudio
  - vstest


# VARIABLES
variables:
- name: Parameters.solution
  value: '**\*.sln'
- name: BuildPlatform
  value: 'any cpu'
- name: BuildConfiguration
  value: 'release'
- name: InfraExist
  value: 'True'

steps:
# BUILD TASKS
- task: NuGetToolInstaller@0
  condition: eq(variables['InfraExist'], 'False')
  displayName: 'Use NuGet 4.4.1'
  inputs:
    versionSpec: 4.4.1

- task: NuGetCommand@2
  condition: eq(variables['InfraExist'], 'False')
  displayName: 'NuGet restore'
  inputs:
    restoreSolution: '$(Parameters.solution)'

- task: VSBuild@1
  condition: eq(variables['InfraExist'], 'False')
  displayName: 'Build solution **\*.sln'
  inputs:
    solution: '$(Parameters.solution)'
    platform: '$(BuildPlatform)'
    configuration: '$(BuildConfiguration)'

- task: VSTest@2
  condition: eq(variables['InfraExist'], 'False')
  displayName: 'VsTest - testAssemblies'
  inputs:
    testAssemblyVer2: |
     **\$(BuildConfiguration)\*test*.dll
     !**\obj\**
    platform: '$(BuildPlatform)'
    configuration: '$(BuildConfiguration)'

- task: PublishSymbols@2
  condition: eq(variables['InfraExist'], 'False')
  displayName: 'Publish symbols path'
  inputs:
    SearchPattern: '**\bin\**\*.pdb'
    PublishSymbols: false
  continueOnError: true

- task: CopyFiles@2
  condition: eq(variables['InfraExist'], 'False')
  displayName: 'Copy Files to: $(build.artifactstagingdirectory)'
  inputs:
    SourceFolder: '$(system.defaultworkingdirectory)'
    Contents: |
     **\bin\$(BuildConfiguration)\**\*.exe
     **\*.ps1
    TargetFolder: '$(build.artifactstagingdirectory)'
  #condition: succeededOrFailed()

- task: PublishBuildArtifacts@1
  condition: eq(variables['InfraExist'], 'False')
  displayName: 'Publish Artifact: drop'
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)'
  #condition: succeededOrFailed()

# RELEASE TASKS
- task: AzureResourceGroupDeployment@2
  condition: eq(variables['InfraExist'], 'False')
  displayName: 'Azure Deployment: Create VNET'
  inputs:
    azureSubscription: 'ArpanRM-SC'
    resourceGroupName: ECIF
    location: 'East US'
    templateLocation: 'URL of the file'
    csmFileLink: 'https://raw.githubusercontent.com/ArpanBalpande/Simple-Calculator/master/ARMTemplates/vnet-one-subnet.json'
    csmParametersFileLink: 'https://raw.githubusercontent.com/ArpanBalpande/Simple-Calculator/master/ARMTemplates/vnet-one-subnet.parameters.json'

- task: AzureResourceGroupDeployment@2
  condition: eq(variables['InfraExist'], 'False')
  displayName: 'Azure Deployment: Create Storage Account'
  inputs:
    azureSubscription: 'ArpanRM-SC'
    resourceGroupName: ECIF
    location: 'East US'
    templateLocation: 'URL of the file'
    csmFileLink: 'https://raw.githubusercontent.com/ArpanBalpande/Simple-Calculator/master/ARMTemplates/storage-account-create.json'
    csmParametersFileLink: 'https://raw.githubusercontent.com/ArpanBalpande/Simple-Calculator/master/ARMTemplates/storage-account-create.parameters.json'

- task: PackerBuild@1
  condition: eq(variables['InfraExist'], 'False')
  displayName: 'Build immutable image'
  inputs:
    ConnectedServiceName: 'ArpanRM-SC'
    managedImageName: SimCalImage
    location: eastus
    storageAccountName: simcalsa
    azureResourceGroup: ECIF
    packagePath: '$(build.artifactstagingdirectory)'
    deployScriptPath: InstallCal.ps1

- task: AzureResourceGroupDeployment@2
  condition: eq(variables['InfraExist'], 'False')
  displayName: 'Azure Deployment: Create VMSS'
  inputs:
    azureSubscription: 'ArpanRM-SC'
    resourceGroupName: ECIF
    location: 'East US'
    templateLocation: 'URL of the file'
    csmFileLink: 'https://raw.githubusercontent.com/ArpanBalpande/Simple-Calculator/master/ARMTemplates/custom-image-vmss.json'
    csmParametersFileLink: 'https://raw.githubusercontent.com/ArpanBalpande/Simple-Calculator/master/ARMTemplates/custom-image-vmss.parameters.json'

- task: AzureVmssDeployment@0
  condition: eq(variables['InfraExist'], 'True')
  displayName: 'Azure VMSS simcalvms: Update App'
  inputs:
    azureSubscription: 'ArpanRM-SC'
    action: 'Configure application startup'
    vmssName: simcalvms
    vmssOsType: Windows
    customScriptsDirectory: '$(build.artifactstagingdirectory)'
    customScript: ChangeCal.ps1
    customScriptsStorageAccount: simcalsa